#   Config files for PyBackup.py
#
#   Use single quotes :-(
#
#   March 2020   Kevin Scott


title = 'PyBackup config file'

# version information
[INFO]
myVERSION = '2020.10'
myNAME    = 'PyBackup'

